### ISSUE TITLE
Resource route renaming

### ISSUE THREAD

**Issue by DZ8540** [adonisjs/http-server#66]
## Package version

<img width="310" alt="image" src="https://user-images.githubusercontent.com/50152205/197956251-36e2d331-76bd-4c05-b038-0736fd19c61c.png">

## Node.js and npm version

<img width="521" alt="image" src="https://user-images.githubusercontent.com/50152205/197956357-d5a067a0-432c-4033-8921-d1e53118021a.png">

## Sample Code (to reproduce the issue)
In routes file:
```js
Route.resource('/uploadTutorials', 'UploadTutorialsController').as('uploadTutorials')
```

In view:
```html
// Not worked
{{ route('uploadTutorials.index') }}

// Worked
{{ route('upload_tutorials.index') }}
```

List of routes:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/50152205/197957015-e66e78e4-16dc-4d89-8b24-94f32505a833.png">

**Comment by thetutlage** [comment]
Hello 👋

Yes, this is intentional. https://github.com/adonisjs/http-server/blob/develop/src/Router/Resource.ts#L216

Should it be transformed to snake case can be debatable. But, changing it in anyway will lead to a breaking change. So, I will hold onto it and have a discussion before the next major release

**Comment by thetutlage** [comment]
It will be fixed in v6.
